# Generated by Django 4.1.7 on 2023-04-07 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ContainerizedWorkshops', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='snippets',
            field=models.ManyToManyField(blank=True, to='ContainerizedWorkshops.snippet'),
        ),
        migrations.AlterField(
            model_name='workshop',
            name='tunneled_ports',
            field=models.ManyToManyField(blank=True, to='ContainerizedWorkshops.tunneledport'),
        ),
    ]
