# Generated by Django 4.1.7 on 2023-04-07 22:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ContainerizedWorkshops', '0002_alter_workshop_snippets_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='participants',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
