# Generated by Django 4.1.7 on 2023-04-13 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ContainerizedWorkshops", "0003_alter_workshop_participants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="snippet",
            name="format",
        ),
        migrations.AddField(
            model_name="snippet",
            name="bash_commands",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="snippet",
            name="powershell_commands",
            field=models.TextField(default=""),
            preserve_default=False,
        ),
    ]
