name: vscode-base

on:
  push:
    paths:
      - example-workshops/vscode-base/**

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: ./example-workshops/vscode-base
          file: ./example-workshops/vscode-base/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/vscode-base:latest
